### ISSUE TITLE
CMOVZ     edx, ebx   //  RDX = 0x00000000ffff5f4f   RDX = 0xffffffffffff5f4f

### ISSUE THREAD

**Issue by icyfox168168** [bitdefender/bddisasm#66] opened 2022-07-15 21:27 UTC
RDX = 0x00000000ffff5f4f   RDX = 0xffffffffffff5f4f

__attribute__((naked)) long long  asmadc()
{
    __asm
    {
          push rbx
          push 0x216
          popf
          mov rdx, 0xffffffffffff5f4f
          mov rbx, 0x00000001405d7c25
          CMOVZ     edx, ebx
          mov rax,rdx
          pop rbx
          ret
    }

"\x53\x68\x16\x02\x00\x00\x9D\x48\xC7\xC2\x4F\x5F\xFF\xFF\x48\xBB\x25\x7C\x5D\x40\x01\x00\x00\x00\x0F\x44\xD3\x48\x89\xD0\x5B\xC3"
}

**Comment by vlutas** [comment] 2022-07-16 09:33
Hello! Thanks for reporting this! The problem is fixed in https://github.com/bitdefender/bddisasm/commit/6dda2c122cd7e3132c2872d61804666dc5ce3f51.

**Closed by vlutas** 2022-07-16 09:33 UTC
